# Batch analysis

The `Batch:` class allows users to analyze the tax liabilities of a batch of filing units under current law and under a tax policy reform. 

## Inputs

The class is initialized with a file path to CSV input -- each column contains data on a different tax information variable (e.g. year, marital status, wages, etc.) and each row represents a different filing unit. A detailed discussion of the inputs is [here](https://github.com/PSLmodels/Tax-Cruncher/blob/master/docs/INPUT_INSTRUCTIONS.md).

In [1]:
# import the Batch class
from taxcrunch.multi_cruncher import Batch
import os

In [2]:
# path to input csv file
CURRENT_PATH = os.path.abspath(os.path.dirname('file'))
path = os.path.join(CURRENT_PATH, "example_input.csv")

# initialize an object of the Batch class
b = Batch(path)

/Users/petermetz/anaconda3/envs/taxcrunch-env/lib/python3.7/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/Users/petermetz/anaconda3/envs/taxcrunch-env/lib/python3.7/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/Users/petermetz/anaconda3/envs/taxcrunch-env/lib/python3.7/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/Users/petermetz/anaconda3/envs/taxcrunch-env/lib/python3.7/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)

## Outputs

Now, we can create a few tables that will show us a detailed breakdown of each filing unit's tax liabilities.

- The `create_table()` method returns a Pandas DataFrame in which each row is a filing unit and each column is an aspect of its tax burden under current law or policy reform. The `write_output_file()` method writes the table as a CSV file.

- The `create_diff_table()` method returns a difference table, where each column shows the difference between liabilities under current law and under policy reform. The `write_diff_file()` method writes the difference table as a CSV file.

To analyze a policy reform, specify the `reform_file` argument in any of the table-making methods. You may enter the file path to a json reform file, a dictionary, or the URL to a reform in the [Tax-Calculator repository](https://github.com/PSLmodels/Tax-Calculator/tree/master/taxcalc/reforms). Make sure that you reform adheres to Tax-Calculator [standards](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/reforms/REFORMS.md).

In [3]:
# outputs under current law (no reform)
b.create_table()

,ID,Individual Income Tax,Payroll Tax,Wages,AGI,UI in AGI,OASDI in AGI,Itemized Deductions,Taxable Inc,CTC,...,EITC,AMT Taxable Income,AMT Liability,Net Investment Income Tax,Income Tax Before Credits,FICA,Qualified Business Income Deduction,Payroll Tax MTR,Income Tax MTR,Combined MTR
0,1.0,23425.0000,21119.6,160000.0,164500.0,0.0,0.0,0.0,146150.00,4000.0,...,0.000,164500.0,0.0,0.0,27425.0000,21119.6,0.00,0.029,0.240000,0.269000
1,2.0,-5333.4120,7267.5,47500.0,47800.0,0.0,0.0,0.0,23400.00,2384.0,...,1717.412,47800.0,0.0,0.0,2384.0000,7267.5,0.00,0.153,0.330600,0.483600
2,3.0,30012.9128,10710.0,70000.0,180000.0,0.0,0.0,0.0,153076.72,0.0,...,0.000,180000.0,0.0,0.0,30012.9128,10710.0,14723.28,0.153,0.404736,0.557736
3,4.0,7589.0000,18819.0,123000.0,124200.0,0.0,0.0,0.0,99800.00,6000.0,...,0.000,124200.0,0.0,0.0,13589.0000,18819.0,0.00,0.153,0.220000,0.373000
4,5.0,50318.6000,23729.6,250000.0,301200.0,0.0,0.0,0.0,266800.00,2000.0,...,0.000,301200.0,0.0,45.6,52273.0000,23729.6,10000.00,0.038,0.240000,0.278000
5,6.0,-529.0000,1683.0,11000.0,11000.0,0.0,0.0,0.0,0.00,0.0,...,529.000,11000.0,0.0,0.0,0.0000,1683.0,0.00,0.153,0.000000,0.153000
6,7.0,-3368.6680,5967.0,39000.0,39250.0,0.0,0.0,0.0,20900.00,2201.0,...,1569.668,39250.0,0.0,0.0,2201.0000,5967.0,0.00,0.153,0.330600,0.483600

In [4]:
# outputs under reform
reform_path = os.path.join(CURRENT_PATH, "../taxcrunch/tests/test_reform.json")
b.create_table(reform_file=reform_path)

,ID,Individual Income Tax,Payroll Tax,Wages,AGI,UI in AGI,OASDI in AGI,Itemized Deductions,Taxable Inc,CTC,...,EITC,AMT Taxable Income,AMT Liability,Net Investment Income Tax,Income Tax Before Credits,FICA,Qualified Business Income Deduction,Payroll Tax MTR,Income Tax MTR,Combined MTR
0,1.0,29986.608950,21119.6,160000.0,164500.0,0.0,0.0,0.0,142004.06,0.000,...,0.000000,164500.0,942.53005,0.0,29986.60895,21119.6,0.0,0.029,0.3250,0.3540
1,2.0,-3516.920764,7267.5,47500.0,47800.0,0.0,0.0,0.0,13323.66,1302.366,...,1819.286764,47800.0,0.00000,0.0,1302.36600,7267.5,0.0,0.153,0.3106,0.4636
2,3.0,38709.758300,10710.0,70000.0,180000.0,0.0,0.0,0.0,169118.24,0.000,...,0.000000,180000.0,0.00000,0.0,38709.75830,10710.0,0.0,0.153,0.2800,0.4330
3,4.0,11103.636500,18819.0,123000.0,124200.0,0.0,0.0,0.0,89723.66,2290.000,...,0.000000,124200.0,0.00000,0.0,13393.63650,18819.0,0.0,0.153,0.3000,0.4530
4,5.0,64838.915900,23729.6,250000.0,301200.0,0.0,0.0,0.0,275198.88,0.000,...,0.000000,301200.0,124.68090,45.6,64793.31590,23729.6,0.0,0.038,0.3500,0.3880
5,6.0,-533.620000,1683.0,11000.0,11000.0,0.0,0.0,0.0,0.00,0.000,...,533.620000,11000.0,0.00000,0.0,0.00000,1683.0,0.0,0.153,0.0000,0.1530
6,7.0,-1874.218124,5967.0,39000.0,39250.0,0.0,0.0,0.0,16754.06,1777.189,...,1651.407124,39250.0,0.00000,0.0,1777.18900,5967.0,0.0,0.153,0.3606,0.5136

In [5]:
b.create_diff_table(reform_file=reform_path)

,ID,Individual Income Tax Diff,Payroll Tax Diff,Wages Diff,AGI Diff,UI in AGI Diff,OASDI in AGI Diff,Itemized Deductions Diff,Taxable Inc Diff,CTC Diff,...,EITC Diff,AMT Taxable Income Diff,AMT Liability Diff,Net Investment Income Tax Diff,Income Tax Before Credits Diff,FICA Diff,Qualified Business Income Deduction Diff,Payroll Tax MTR Diff,Income Tax MTR Diff,Combined MTR Diff
0,1.0,6561.608950,0.0,0.0,0.0,0.0,0.0,0.0,-4145.94,-4000.000,...,0.000000,0.0,942.53005,0.0,2561.60895,0.0,0.00,0.0,0.085000,0.085000
1,2.0,1816.491236,0.0,0.0,0.0,0.0,0.0,0.0,-10076.34,-1081.634,...,101.874764,0.0,0.00000,0.0,-1081.63400,0.0,0.00,0.0,-0.020000,-0.020000
2,3.0,8696.845500,0.0,0.0,0.0,0.0,0.0,0.0,16041.52,0.000,...,0.000000,0.0,0.00000,0.0,8696.84550,0.0,-14723.28,0.0,-0.124736,-0.124736
3,4.0,3514.636500,0.0,0.0,0.0,0.0,0.0,0.0,-10076.34,-3710.000,...,0.000000,0.0,0.00000,0.0,-195.36350,0.0,0.00,0.0,0.080000,0.080000
4,5.0,14520.315900,0.0,0.0,0.0,0.0,0.0,0.0,8398.88,-2000.000,...,0.000000,0.0,124.68090,0.0,12520.31590,0.0,-10000.00,0.0,0.110000,0.110000
5,6.0,-4.620000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000,...,4.620000,0.0,0.00000,0.0,0.00000,0.0,0.00,0.0,0.000000,0.000000
6,7.0,1494.449876,0.0,0.0,0.0,0.0,0.0,0.0,-4145.94,-423.811,...,81.739124,0.0,0.00000,0.0,-423.81100,0.0,0.00,0.0,0.030000,0.030000

## Behavioral Responses

Finally, the `Batch` class gives users the option to estimate behavioral responses to a tax policy reform. The three optional arguments for behavioral response analysis are:

- `be_sub`: substitution elasticity of taxable income
- `be_inc`: income elasticity of taxable income
- `be_cg`: semi-elasticity of long-term capital gains

The implementation of these elasticities is carried out by the [Behavioral-Responses](https://github.com/PSLmodels/Behavioral-Responses) project. Further discussion on the definition of the elasticities can be found [here](https://github.com/PSLmodels/Behavioral-Responses/blob/master/behresp/behavior.py)

In [6]:
b.create_table(reform_file=reform_path, be_sub=0.25)

,ID,Individual Income Tax,Payroll Tax,Wages,AGI,UI in AGI,OASDI in AGI,Itemized Deductions,Taxable Inc,CTC,...,EITC,AMT Taxable Income,AMT Liability,Net Investment Income Tax,Income Tax Before Credits,FICA,Qualified Business Income Deduction,Payroll Tax MTR,Income Tax MTR,Combined MTR
0,1.0,28632.687498,21002.093420,155948.048963,160334.087840,0.0,0.0,0.0,137838.147840,0.000000,...,0.000000,160334.087840,636.885538,0.0,28632.687498,21002.093420,0.0,0.029,0.3250,0.3540
1,2.0,-3455.628472,7297.502784,47696.096626,47997.335131,0.0,0.0,0.0,13520.995131,1322.099513,...,1777.727985,47997.335131,0.000000,0.0,1322.099513,7297.502784,0.0,0.153,0.3106,0.4636
2,3.0,41286.252008,11257.504913,73578.463483,189201.763243,0.0,0.0,0.0,178320.003243,0.000000,...,0.000000,189201.763243,0.000000,0.0,41286.252008,11257.504913,0.0,0.153,0.2800,0.4330
3,4.0,10252.463786,18389.096100,120190.170591,121362.757622,0.0,0.0,0.0,86886.417622,2431.862119,...,0.000000,121362.757622,0.000000,0.0,12684.325905,18389.096100,0.0,0.153,0.3000,0.4530
4,5.0,61381.180801,23489.811247,241731.422294,291238.017580,0.0,0.0,0.0,265236.897580,0.000000,...,0.000000,291238.017580,0.000000,0.0,61381.180801,23489.811247,0.0,0.038,0.3500,0.3880
5,6.0,-533.620000,1683.000000,11000.000000,11000.000000,0.0,0.0,0.0,0.000000,0.000000,...,533.620000,11000.000000,0.000000,0.0,0.000000,1683.000000,0.0,0.153,0.0000,0.1530
6,7.0,-1969.553004,5926.807735,38737.305460,38985.621520,0.0,0.0,0.0,16489.681520,1737.532228,...,1707.085232,38985.621520,0.000000,0.0,1737.532228,5926.807735,0.0,0.153,0.3606,0.5136

In [7]:
b.create_diff_table(reform_file=reform_path, be_sub=0.25)

,ID,Individual Income Tax Diff,Payroll Tax Diff,Wages Diff,AGI Diff,UI in AGI Diff,OASDI in AGI Diff,Itemized Deductions Diff,Taxable Inc Diff,CTC Diff,...,EITC Diff,AMT Taxable Income Diff,AMT Liability Diff,Net Investment Income Tax Diff,Income Tax Before Credits Diff,FICA Diff,Qualified Business Income Deduction Diff,Payroll Tax MTR Diff,Income Tax MTR Diff,Combined MTR Diff
0,1.0,5207.687498,-117.506580,-4051.951037,-4165.912160,0.0,0.0,0.0,-8311.852160,-4000.000000,...,0.000000,-4165.912160,636.885538,0.0,1207.687498,-117.506580,0.00,0.0,0.085000,0.085000
1,2.0,1877.783528,30.002784,196.096626,197.335131,0.0,0.0,0.0,-9879.004869,-1061.900487,...,60.315985,197.335131,0.000000,0.0,-1061.900487,30.002784,0.00,0.0,-0.020000,-0.020000
2,3.0,11273.339208,547.504913,3578.463483,9201.763243,0.0,0.0,0.0,25243.283243,0.000000,...,0.000000,9201.763243,0.000000,0.0,11273.339208,547.504913,-14723.28,0.0,-0.124736,-0.124736
3,4.0,2663.463786,-429.903900,-2809.829409,-2837.242378,0.0,0.0,0.0,-12913.582378,-3568.137881,...,0.000000,-2837.242378,0.000000,0.0,-904.674095,-429.903900,0.00,0.0,0.080000,0.080000
4,5.0,11062.580801,-239.788753,-8268.577706,-9961.982420,0.0,0.0,0.0,-1563.102420,-2000.000000,...,0.000000,-9961.982420,0.000000,-45.6,9108.180801,-239.788753,-10000.00,0.0,0.110000,0.110000
5,6.0,-4.620000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,4.620000,0.000000,0.000000,0.0,0.000000,0.000000,0.00,0.0,0.000000,0.000000
6,7.0,1399.114996,-40.192265,-262.694540,-264.378480,0.0,0.0,0.0,-4410.318480,-463.467772,...,137.417232,-264.378480,0.000000,0.0,-463.467772,-40.192265,0.00,0.0,0.030000,0.030000